---
develop:
  handler:
    dbfile: /var/lib/bounced_emails.db
    temporary_threshold: 3
    domains:
      opensap.info:
        endpoint: http://localhost/stop-notification
      openhpi.de:
        endpoint: http://localhost/stop-notification
  amqp:
    url: amqp://mwiesner:geheim@localhost/%2f
    queue: bouncedemails
    no_ack: True

production:
  handler:
    dbfile: /var/lib/bounced_emails.db
    temporary_threshold: 3
    domains:
      opensap.info:
        endpoint: http://open.hpi.de/account/stop-notification
      openhpi.de:
        endpoint: http://opensap.info/account/stop-notification
  amqp:
    url: amqp://mwiesner:geheim@10.210.0.30/%2f
    queue: bouncedemails
    no_ack: True