---
develop:
  handler:
    dbfile: /tmp/bounced_emails.db
    permanent_bounced_emails_path: /tmp/permanent_bounced_emails
    temporary_threshold: 3
    domains:
      mydomain.de:
        base_url: http://localhost:7001
      openhpi.de:
        base_url: http://localhost:7001
      opensap.info:
        base_url: http://localhost:7001
  amqp:
    url: amqp://mwiesner:geheim@localhost/%2fbouncedemails
    queue: bouncedemails

production:
  handler:
    dbfile: /var/lib/bounced_emails.db
    permanent_bounced_emails_path: /var/lib/permanent_bounced_emails
    temporary_threshold: 3
    domains:
      opensap.info:
        base_url: http://10.210.0.32:7001
      openhpi.de:
        base_url: http://10.210.0.30:7001
  amqp:
    url: amqp://bouncedemails:h6kPPxkhZ3PVxSGUtr2H@10.210.0.30/%2fbouncedemails
    queue: bouncedemails