---
develop:
  handler:
    dbfile: /var/lib/bounced_emails.db
    permanent_bounced_emails_path: /var/lib/permanent_bounced_emails
    temporary_threshold: 3
  suspender:
    mydomain.de:
      endpoint: http://localhost/emails/suspend

  amqp:
    url: amqp://mwiesner:geheim@localhost/%2fbouncedemails
    queue: bouncedemails

production:
  handler:
    dbfile: /var/lib/bounced_emails.db
    permanent_bounced_emails_path: /var/lib/permanent_bounced_emails
    temporary_threshold: 3

  suspender:
    opensap.info:
      base_url: http://10.210.0.32:7001
    openhpi.de:
      base_url: http://10.210.0.30:7001
    mydomain.de:
      endpoint: http://mydomain.de/emails/suspend/

  amqp:
    url: amqp://bouncedemails:h6kPPxkhZ3PVxSGUtr2H@10.210.0.30/%2fbouncedemails
    queue: bouncedemails